@expressUrl = http://127.0.0.1:4000
@fastapiUrl = http://127.0.0.1:8000

### 1. Express 로그인 후 JWT를 저장
# @name login
POST {{expressUrl}}/api/auth/login
Content-Type: application/json

{
  "userId": "내_아이디",
  "password": "내_비밀번호"
}

###

### 2. FastAPI 추천 API 요청
PPOST {{fastapiUrl}}/api/recommendations
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
  "minBudget": 3000,
  "maxBudget": 5000,
  "lifestyles": ["출퇴근", "가족 이동"],
  "bodyTypes": ["SUV"],
  "powertrains": ["하이브리드"],
  "priorities": ["가격", "공간"],
  "features": [],
  "usageTypes": ["구매"],
  "origins": ["국산"]
}